name: Terraform Plan

# configure to run on merges to 'main' branch
on:
  workflow_dispatch
  #push:
    #branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # be sure to authenticate with cloud provider
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: '${{ secrets.TF_USER_AWS_KEY }}'
          aws-secret-access-key: '${{ secrets.TF_USER_AWS_SECRET }}'
          aws-region: us-east-1


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    # generate Terraform Plan and store in .tfplan file
    - name: Terraform Plan
      run: terraform plan -out:terraform.tfplan

    # commit Terraform plan if running on 'main' branch
    # commit is made to the 'terraform-plan' branch
    - name: Commit Terraform Plan for Approval
      if: github.ref == 'refs/heads/main'
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: 'Terraform Plan'
        branch: 'terraform-plan'
        base: 'main'
        token: ${{ secrets.GITHUB_TOKEN }}
